# Generated by Django 2.2.1 on 2019-05-16 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=10, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, help_text='Height in centimeters', null=True)),
                ('birth_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('chest', models.PositiveSmallIntegerField(blank=True, help_text='Chest Size in centimeters', null=True)),
                ('weight', models.PositiveSmallIntegerField(blank=True, help_text='Weight in kilograms', null=True)),
                ('kanji', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=255, null=True)),
                ('jp_name', models.CharField(max_length=255, null=True)),
                ('media_type', models.CharField(default='game', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appearances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spoiler', models.BooleanField(default=False)),
                ('primary_media', models.BooleanField(default=True)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='char_info.Character')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='char_info.Media')),
            ],
        ),
    ]
