# Generated by Django 2.2.1 on 2019-05-16 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('char_info', '0002_auto_20190516_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('number', models.SmallIntegerField(help_text='The number of the chapter in the game.\nStarts at 0 for the Prologue')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='char_info.Media')),
            ],
        ),
        migrations.CreateModel(
            name='Talents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spoiler', models.BooleanField(default=False)),
                ('talent', models.CharField(max_length=80)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='char_info.Character')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='char_info.Media')),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=4096, null=True)),
                ('spoiler', models.BooleanField(default=False)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='char_info.Character')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='char_info.Media')),
            ],
        ),
        migrations.CreateModel(
            name='Murders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='char_info.Chapters')),
                ('murdered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='murdered', to='char_info.Character')),
                ('murderer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='murderer', to='char_info.Character')),
            ],
        ),
    ]
