# Generated by Django 2.2.1 on 2019-05-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('char_info', '0003_chapters_murders_quotes_talents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appearances',
            new_name='Appearance',
        ),
        migrations.RenameModel(
            old_name='Chapters',
            new_name='Chapter',
        ),
        migrations.RenameModel(
            old_name='Murders',
            new_name='Murder',
        ),
        migrations.RenameModel(
            old_name='Quotes',
            new_name='Quote',
        ),
        migrations.RenameModel(
            old_name='Talents',
            new_name='Talent',
        ),
    ]
