# Generated by Django 2.2.1 on 2019-05-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('char_info', '0005_auto_20190519_1146'), ('char_info', '0006_auto_20190519_1202')]

    dependencies = [
        ('char_info', '0004_auto_20190516_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown'), ('?', '?')], max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='appearance',
            constraint=models.UniqueConstraint(fields=('character', 'media'), name='unique_appearance'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('media', 'number'), name='unique_chapter'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_character'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.UniqueConstraint(fields=('english_name', 'media_type'), name='unique_media'),
        ),
        migrations.AddConstraint(
            model_name='murder',
            constraint=models.UniqueConstraint(fields=('murderer', 'murdered', 'chapter'), name='unique_murder'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('character', 'quote', 'media'), name='unique_quote'),
        ),
        migrations.AddConstraint(
            model_name='talent',
            constraint=models.UniqueConstraint(fields=('character', 'media', 'talent'), name='unique_talent'),
        ),
        migrations.AlterField(
            model_name='character',
            name='birth_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.CheckConstraint(check=models.Q(('birth_day__gte', 1), ('birth_day__lte', 31)), name='birth_day_limit'),
        ),
    ]
